// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQHhqkZRpXvCbnOnEmXyg7DLGMIgx9_Ew',
    appId: '1:247894978562:web:4c9bde4197d5018adcb71b',
    messagingSenderId: '247894978562',
    projectId: 'g8te-pass',
    authDomain: 'g8te-pass.firebaseapp.com',
    storageBucket: 'g8te-pass.appspot.com',
    measurementId: 'G-YT7ND7ELF7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuKwuPXneN8LrWytYDj7Z0IKU7ww0G0_Y',
    appId: '1:247894978562:android:17077c2bdd17af82dcb71b',
    messagingSenderId: '247894978562',
    projectId: 'g8te-pass',
    storageBucket: 'g8te-pass.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeFjcer58pcgXvyWQsAdynOtXNYxlm4vI',
    appId: '1:247894978562:ios:8a3376f32d677fb7dcb71b',
    messagingSenderId: '247894978562',
    projectId: 'g8te-pass',
    storageBucket: 'g8te-pass.appspot.com',
    iosClientId: '247894978562-lfjetbst2848i6r38gbsp3nbe0rtf74s.apps.googleusercontent.com',
    iosBundleId: 'ph.jpdc.com',
  );
}
